#!/bin/bash

# Author : Arunkumar
# Date created : 12/10/2021
# Date Modified : 22/10/2021

# Description :
# This bash script will help us to backup sql database
echo "$userpass" |sudo -S service mysql start
cd ~/mybashes
if [ ! -d /opt/backups ]; then
	sudo -S mkdir /opt/backups
fi
backupfilename="DB-backup-$(date '+%d-%m-%Y')"


sudo -S mysqldump -u "$MYSQLUSER" -p"$MYSQLPASS" "crud_db" > "$backupfilename" --no-tablespaces 2>>error.txt
cd ~/mybashes/
echo $PWD
if [ ! -f /opt/backups/sqlbackup.tar ]; then
	echo "Archive File Creation...." >> ~/Desktop/logs.txt
	sudo -S tar cvf "/opt/backups/sqlbackup.tar" -C "$PWD" "$backupfilename" 
else
	echo "Archive File Updation" >> ~/Desktop/logs.txt
	sudo -S tar rvf "/opt/backups/sqlbackup.tar" -C "$PWD" "$backupfilename"
fi
sudo rm "$PWD/$backupfilename" 2>>error.txt
echo "Tar archive backup done in opt/backup "

